### ISSUE TITLE
input content into rest of site

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#112]
*a/c*
- input rest of content to site using netlify cms

**Comment by racheldds** [comment]
Done. Content input complete for 'Our Work' and 'Our Team' pages v1. Still need to flesh out the three fly-out pages under 'Our Work', as well as build out the 'Join Us' and 'Media' pages/input content. All in progress.

**Comment by racheldds** [comment]
Alright, as of 5/7 COB additional content has been input for: 
- 'Our Work' fly-outs (Portfolios, Product Developments, Ongoing Technical Advice)
- 'Join Us' main page and following 'success' page

**Still in progress:** 
- 'Media' page — there are some CMS issues/tweaks being worked through, and, I still need to pull all of the content for 'DDS In The News'. Hoping to have content inputs done for this page and all its fly-outs (Announcements, Blogs, DDS In The News) by early next week since I'm trying to be OOO 5/8.

**Comment by racheldds** [comment]
As of 5/11; **done will all content inputs**

Need to determine plan for blog posts (adding new) and imagery associated, but otherwise we should be good on content.
