### ISSUE TITLE
BK Feedback

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#225]
mission/vision phil/scarlett feedback intent

**Comment by ashhath01** [comment]
swap 
- portfolios for firefighting
- technical advice for phone a nerd

- more white space for body copy, paragraph 

form: "Product Management and something long"

- more photos (see roro)

About Us, under "values":
We refer to the DoD in 3 different ways (Department, DoD, etc.)
"Signal intent" isn't clear.
Our Work:
"Using design and technology to improve government services, strengthen national defense, and care for military members and their families." is not a complete sentence.
"Engagement Categories" is spelled wrong.
Should have the numbers of the Categories also bold.
The Categories are not totally accurate. Portfolios, Projects, Firefighting, Technical Advice, Discovery Sprints. I could see leaving out Discovery Sprints as it folds into either projects or technical advice, but our Firefighting should be in there. MySymptoms.mil goes in that category
The text is weird when you go to the sub-page of the Engagement Categories.
Our Team:
Missing "s" after contractors.
Media
Think you can just say "News" instead of "DDS in the news"

**Comment by racheldds** [comment]
swap
- portfolios for firefighting **(fixed, but now where do we put Hack the Pentagon?? still will need to update copy in this section once I receive the deck link that was discussed on the call)**
- technical advice for phone a nerd **(fixed)** 
- more white space for body copy, paragraph **(I think this is a Jeff thing, not a Rachel thing)**

About Us, under "values":
- We refer to the DoD in 3 different ways (Department, DoD, etc.) **(fixed)**
- "Signal intent" isn't clear. **(I don't know what the request/edit is here. Signal intent is listed in one of the values already.)**

Our Work:
- "Using design and technology to improve government services, strengthen national defense, and care for military members and their families." is not a complete sentence. **(fixed)**
- "Engagement Categories" is spelled wrong. **(fixed)**
- Should have the numbers of the Categories also bold. **(I think this is a CMS/Jeff thing; not a Rachel thing)**
- The Categories are not totally accurate. Portfolios, Projects, Firefighting, Technical Advice, Discovery Sprints. I could see leaving out Discovery Sprints as it folds into either projects or technical advice, but our Firefighting should be in there. MySymptoms.mil goes in that category **(fixed per the first list of items in this comment)**
- The text is weird when you go to the sub-page of the Engagement Categories. **(Think this is a Jeff thing not Rachel thing, I don't see any major issues with the text on my end)**

Our Team:
- Missing "s" after contractors. **(fixed)**

Media
- Think you can just say "News" instead of "DDS in the news" **(fixed, though looks like someone did it before I got in there)**


@jhackshaw-dds for all the changes to the pages under Our Work, I think we'll need to change the redirect links too (the ones that look like this: /work/portfolios). I've changed the titles via CMS copy, but are you able to manage all the updates to redirect pages, etc.? I don't want to mess that up. Should be Firefighting, Projects, and Phone A Friend.

**Comment by jhackshaw-dds** [comment]
@racheldds Let me know if it looks alright the way it is now, it's easy for me to change too. I changed to:

/work/fire-fighting
/work/phone-a-friend
/work/projects

**Comment by racheldds** [comment]
Looks perfect, thanks @jhackshaw-dds.
