### ISSUE TITLE
Content stack rank

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#71]

**Comment by ashhath01** [comment]
- Let's look at the current site
- Look at content doc
- See what needs to be in there first 
- Include eng & design for awareness as optional

*A/C*
- Stack ranked list of content priorities

**Comment by racheldds** [comment]
Thoughts: If I had to rank the content "pages" for inclusion and priorities it would be as follows:

1. About Us
2. Our Work
3. Join Us
4. Media
5. Our Team
6. Rogue Squadron (standalone website integration)

Legal disclaimers/the footer will need to be prioritized/updated no matter what in order to push out the new site. 

While the "Our Team" page is definitely important, I think it's not as vital to the initial makeover. Current site has About (one measly paragraph), Projects (six old/vague write ups), Team (one measly paragraph), Join Us (an email link), Marketplace (not helpful going forward), News (links very old media articles/hasn't been updated in ages).

For folks to look at a new site and understand us, I think pointing to the refreshed "About Us" page along with the projects we do, how to join the team, and DDS in the **recent** news along with other announcements is most beneficial. We can tack on team headshots and fun facts, as well as RS integration down the line if needed.

**Comment by ChristanJohnson** [comment]
Agree with rank of content and the state of the current website.  

Rachel where do you think the blog content should reside?

**Comment by racheldds** [comment]
CJ, right now in the content/copy doc I have the blog as a subsection on the "Media" page. I think it makes most sense there — it will be our "owned" blog for thought leadership content, recruiting content, and team stories.

**Comment by ChristanJohnson** [comment]
Sounds good, thanks Rachel.

**Comment by ashhath01** [comment]
fyi @marieksmith for design awareness of content to coincide with your site map. maybe building out about us is the first page?? up to you of course.

**Comment by ashhath01** [comment]
adding marie to this issue for tracking
