### ISSUE TITLE
MVP content approvals

### ISSUE THREAD

**Issue by ashhath01** [deptofdefense/dds.mil#75]
acceptance criteria:
- critical reading for:
  - spelling, grammar
  - readability
  - content accuracy
  - other awareness

**Comment by ashhath01** [comment]
Blessed by:
- [ ] DDS volunteer
- [ ] Someone who does english good
- [ ] CJ
- [ ] Katie
- [ ] Brett

**Comment by racheldds** [comment]
Thoughts: Other than me, open to ideas for the "copy editor" volunteer to only look at the content with the lens of making sure spelling, punctuation, etc. is good. This is usually what I am tasked for across group when help is needed — maybe we have a lawyer like Susan take a look? For "DDS volunteer" I'm thinking we want someone who has been on the team longer than us and really knows the group. Maybe RoRo/Anil? 

As of 4/3 I believe CJ has already reviewed, but we can discuss on next sync.

**Comment by ChristanJohnson** [comment]
Reviewing content Rachel has created.  Looking forward to discussing this during the next sync.

**Comment by ashhath01** [comment]
ash to ask scarlett & phil for copy review with 1 week turnaround.

**Comment by scarlettdds** [comment]
First things first, ❤️❤️❤️

I think the new site captures the spirit of DDS and will help with recruitment.

Some copy feedback on the homepage, About Us page, and Our Team page. I'll circle back on Our Work and Join Us later.

**Homepage**

- I think the mission statement could be tighter. Maybe something like:

> The Defense Digital Service (DDS) is a SWAT team of nerds established by the Secretary of Defense to provide the best in modern technology to bolster national defense. We are designers, product managers, engineers, and data scientists from industry and government who advance critical DoD initiatives.

- What does "Doing work that matters by focusing our time and energy on high-priority undertakings." mean? I don't think anyone would say, "Doing work that doesn't matter by focusing our time and energy on low-priority undertakings," so this feels like a throw-away right now unless we can sharpen.

**About Us**

- Removed a few words, de-jargoned (I think talking about "talent" comes across as weird outside of recruiters talking to recruiters) and shuffled a few things:

>DDS was established by the Secretary of Defense in November 2015 as a SWAT team of nerds that provides the best in modern technical knowledge to bolster national defense.
>
> We are world-class software developers, engineers, data scientists, designers, and product managers from both the private sector, government, and the military. We are headquartered in the Pentagon with outposts in Augusta, GA and Mountain View, CA.
>
>We focus on high-impact projects that advance the Department of Defense's most important initiatives that are critical to the well-being of service members, civilians, and core operations of the Department.

- I feel like the "How We Team" section is a little out of place here. I was going to suggest it in "Our Team," and it looks like it's already there too.

- For the values, the voice should be consistent across. For example, I think we should change the text under "Be brave and tell the truth" so it is also "We ..." and more active. Possibly: "We tell the Department the truth about systems and capabilities — even if it's hard to hear." I also think we should change the text under "Design with users not for them" to something like: "We design directly with users to ensure the product and supporting processes meet needs the first time."

- For the "Ask for forgiveness, not permission" value, I feel like "signal intent" is jargony and inconsistent with the very plain language of the values otherwise. Can we be clearer about what we mean here?

**Our Team**

- Some suggestions to tighten the copy (strikethrough for deletions and bold for additions):

>Our team includes ~~a wide range of unique talent, including~~ world-class software developers, engineers, **data scientists**, designers, product managers, and digital experts from both the private sector and within government. ~~In addition to bringing in private sector and government talent,~~ DDS **also** partners with military services by detailing service members to DDS teams to tackle some of the DoD’s highest priority challenges.
>
>We currently have approximately ~~82~~**80** employees at DDS — a mix of civilian, military, and contractor — spread out across our permanent office spaces.

- I would not say "approximately" and then give a very precise number (82), so I suggest changing to "approximately 80"

**Comment by scarlettdds** [comment]
Only one immediate thought under Our Work. Under Product Developments, could we add mysymptoms.mil? I think that's a compelling example of our capabilities.

Longer term, I think it would be interesting to think about a content strategy around our projects. That's the number one question I get asked from potential candidates. I think this v1 definitely gives a better flavor of the range of work, but I also think it could be more exciting if we had more time and energy to devote to it. I know that's not a v1 task, but wanted to throw it out there.

**Comment by racheldds** [comment]
Copy tweaks made as I saw fit; accepted almost all with the exception of the "ask forgiveness, not permission... and signal intent" value per 5/14 dds.mil standup discussion.

**Comment by ashhath01** [comment]
marking this done unless i'm missing somethign @racheldds @ChristanJohnson
